server:
  port: 8080

########### 数据库
spring:
  datasource:
       name: "yzgl"
       type: com.mysql.cj.jdbc.MysqlDataSource
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3306/yzgl?useSSL=false&serverTimezone=UTC
       username: root
       password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
########### Mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/xml/*Mapper.xml
  type-aliases-package: com.jerry.yzgl.yw.domain
  configuration:
    #驼峰命名规则
    map-underscore-to-camel-case: true



