server:
  port: 8080

########### 数据库
spring:
  datasource:
       name: "yzgl"
       type: com.mysql.cj.jdbc.MysqlDataSource
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3306/yzgl?useSSL=false&serverTimezone=UTC
       username: root
       password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
########### Mybatis
mybatis:
   mapper-locations: classpath:mapper/*Mapper.xml



